version: 2

updates:
  - package-ecosystem: gradle
    directory: /antlr4
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    labels:
      - dependencies
    groups:
      antlr:
        patterns:
          - org.antlr:*
      test:
        patterns:
          - org.junit*
          - org.junit.jupiter:*
          - org.junit.platform:*

  - package-ecosystem: npm
    directory: /antlr-ng
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - npm

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - github-actions
    groups:
      actions:
        patterns:
          - '*'
